spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authz?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  oauth2:
    client:
      clientId: clientapp
      clientSecret: 123456
      accessTokenUri: https://sso-dev.directsale.vn/oauth/token
      userAuthorizationUri: https://sso-dev.directsale.vn/oauth/authorize
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      scope:
        - openid
        - profile
        - email
    resource:
      userInfoUri: https://sso-dev.directsale.vn/user/me

server:
  port : 8082
