CREATE TABLE LOGIN (
    AUTHZ_ID     VARCHAR (50) NOT NULL,
    USERNAME            VARCHAR (250) NOT NULL,
    PASSWORD     VARCHAR (250),
    EMAIL           VARCHAR (250),
    UPDATED_TIMSTM  TIMESTAMP (6),
    PRIMARY KEY ("AUTHZ_ID")
);